apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: spark
spec:
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: minio
  namespace: spark
spec:
  rules:
    - host: minio.kube1
      http:
        paths:
          - path: /
            backend:
              serviceName: minio
              servicePort: 9000
